<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-02-26T23:58:56+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'jhmooserugby',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1456531063,
        'do_page_reindex_check' => false,
    ),
);
