<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-02-27T01:42:36+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'jhmooserugby',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1456531063,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.6',
    ),
);
